services:
  - type: web
    name: go-backend
    env: go
    plan: free
    buildCommand: go build -tags netgo -ldflags "-s -w" -o main .
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        sync: false
